<div class="tvd-row tvd-add-link-row">
	<div class="tvd-col tvd-s4">
		<div class="tvd-input-field">
			<input type="text" class="tvu_leads_directUrl" id="tvu_leads_directUrl"/>
			<label for="tvu_leads_directUrl"><?php echo __( "Add new link", TVE_Ult_Const::T ); ?></label>
		</div>
	</div>
	<div class="tvd-col tvd-s2">
		<button class="tvu_leads_addDirectLink tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green"><?php echo __( "Add Link", TVE_Ult_Const::T ); ?></button>
	</div>
</div>
