<div class="tvd-row tvd-collapse">
	<div class="tvd-col tvd-s8">
		<div class="tvd-vertical-align">
			<a href="<#= label #>" target="_blank"><#= label #></a>
		</div>
	</div>
	<div class="tvd-col tvd-s4">
		<button class="tvu_leads_removeDirectLink tvd-btn-icon tvd-btn-icon-red tvd-right">
			<span class="tvd-icon-delete2"></span>
			<?php echo __("Remove Link", TVE_Ult_Const::T); ?>
		</button>
	</div>
</div>



