<!-- Twitter -->
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://products.askupasoftware.com/php-settings/" data-text="PHP Settings - Easily edit you local php.ini settings in #wordpress" data-via="AskupaSoftware">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<!-- Facebook -->
<iframe src="https://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fproducts.askupasoftware.com%2Fphp-settings%2F&width=80px&layout=button_count&action=like&show_faces=true&share=false&height=21&appId=234976736516821" width="80px" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
<!-- Google -->
<script src="https://apis.google.com/js/platform.js" async defer></script>
<div class="g-plusone" data-size="medium" data-href="http://products.askupasoftware.com/php-settings/"></div>