<div class="tvu-timeline-col tvu-timeline-col-first">
	<a href="javascript:void(0)" id="tvu-add-timeline-event"
	   class="tvu-add-timeline-event tvd-tooltipped" data-tooltip="<?php echo __( "Add new event to timeline", TVE_Ult_Const::T ) ?>" data-position="right">
		<span class="tvd-icon-plus"></span>
	</a>
	<div class="tvu-timeline-date">
		<#= item.getLabel() #>
	</div>
</div>
<div class="tvu-timeline-col tvu-timeline-col-second">
	<p class="tvu-timeline-end tvd-no-margin">
		<?php echo __("Campaign end", TVE_Ult_Const::T) ?>
	</p>
</div>
