<div class="row tcb-delete-template-confirmation">
	<div class="col-xs-12">
		<h4><?php echo __( 'Are you sure?', 'thrive-cb' ); ?></h4>
	</div>
	<div class="col-xs-12 tcb-delete-template-action">
		<div class="row">
			<div class="col-xs-12 tcb-apply-delete-template">
				<h4><?php echo __( 'YES, DELETE', 'thrive-cb' ); ?></h4>
			</div>
			<div class="col-xs-12 tcb-cancel-delete-template">
				<h4><?php echo __( 'NO, KEEP IT', 'thrive-cb' ); ?></h4>
			</div>
		</div>
	</div>
</div>
