<div class="tve-landing-page-text-preview tve-remove-auxiliary-content canvas-mode">
	<div class="tve-border-radius">
		<div class="tve-landing-page-text-controls">
			<div class="tve_left"><?php echo __( 'All text formats', 'thrive-cb' ) ?></div>
			<div id="tcb-close-lp-fonts-icon" class="tve_right tcb-close-lp-fonts"></div>
		</div>
		<div id="tcb-fonts-all-texts-wrapper">
			<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="All Texts" data-apply="h1, h2, h3, h4, h5, h6, p, li" data-all-texts="1">
				<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="All Headings" data-apply="h1, h2, h3, h4, h5, h6" data-element-class="thrv_heading">
					<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="H1" data-apply="h1" data-element-class="thrv_heading" data-tag="h1">
						<div class="thrv_heading">
							<h1>Example H1 Heading</h1>
						</div>
					</div>

					<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="H2" data-apply="h2" data-element-class="thrv_heading" data-tag="h2">
						<div class="thrv_heading">
							<h2>Example H2 Heading</h2>
						</div>
					</div>

					<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="H3" data-apply="h3" data-element-class="thrv_heading" data-tag="h3">
						<div class="thrv_heading">
							<h3>Example H3 Heading</h3>
						</div>
					</div>

					<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="H4" data-apply="h4" data-element-class="thrv_heading" data-tag="h4">
						<div class="thrv_heading">
							<h4>Example H4 Heading</h4>
						</div>
					</div>

					<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="H5" data-apply="h5" data-element-class="thrv_heading" data-tag="h5">
						<div class="thrv_heading">
							<h5>Example H5 Heading</h5>
						</div>
					</div>

					<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="H6" data-apply="h6" data-element-class="thrv_heading" data-tag="h6">
						<div class="thrv_heading">
							<h6>Example H6 Heading</h6>
						</div>
					</div>
				</div>
				<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="Text/Paragraph" data-apply="p, li" data-element-class="thrv_text_element">
					<div class="thrv_text_element">
						<p>An example paragraph text including some <strong>bold text</strong> and some this <em>italic</em> word.</p>
					</div>
				</div>
				<div class="thrv_wrapper thrv-lp-text tcb-no-clone tcb-no-delete tve_no_drag tcb-no-title" data-element-name="Hyperlink" data-apply="a:not(.tcb-button-link)" data-element-class="thrv_text_element">
					<div class="thrv_text_element">
						<p><a href="https://thrivethemes.com" target="_blank">This is a hyperlink.</a></p>
					</div>
				</div>
			</div>
		</div>
		<div class="tcb-panel-right">
			<button id="tcb-close-lp-fonts-btn" class="tcb-btn-green tcb-close-lp-fonts"><?php echo __( 'Close', 'thrive-cb' ) ?></button>
		</div>
	</div>
</div>
