<div class="tvd-col tvd-s6 tvd-ms6 tvd-m4 tvd-l3">
	<div class="tvd-card tvd-small tvd-red">
		<div class="tvd-card-content tvd-center-align">
			<h4 class="tvd-margin-top">
				<?php echo __( 'Are you sure you want to delete this script?', TVE_DASH_TRANSLATE_DOMAIN ) ?>
			</h4>
		</div>
		<div class="tvd-card-action">
			<a class="tvd-modal-close tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tvd-left tvd-waves-effect">
				<?php echo __( 'NO, DON\'T DELETE', TVE_DASH_TRANSLATE_DOMAIN ) ?>
			</a>
			<a class="tvd-submit tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tvd-waves-effect">
				<?php echo __( 'YES, DELETE', TVE_DASH_TRANSLATE_DOMAIN ) ?>
			</a>
		</div>
	</div>
</div>
<a href="javascript:void(0)" class="tvd-modal-action tvd-modal-close tvd-modal-close-x tvd-white-text"><i class="tvd-icon-close2"></i></a>