<div class="api-field">
	<div class="field-description">
		<?php echo __( 'Choose your mailing list', 'thrive-cb' ); ?>
	</div>
	<div class="row">
		<div class="col-xs-9">
			<select class="api-list tve-active-campaign-list" data-name="list">
				<# _.each(api.get('lists'), function(item) { #>
				<#= TVE.tpl( 'util/option', {value:item.id, selected: (api.getConfig('list')==item.id), text: item.name}) #>
				<# } ) #>
			</select>
		</div>

		<div class="col-xs-3">
			<button type="button" class="button-link blue tcb-right click" data-fn="forceGet">
				<?php echo __( 'Reload Lists', 'thrive-cb' ); ?>
			</button>
		</div>
	</div>
</div>
<div class="api-field">
	<div class="field-description margin-top-10">
		<?php echo __( 'Choose the form you want to use:', 'thrive-cb' ); ?>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<select class="tve-api-extra activecampaign-list-form" name="form"></select>
		</div>
	</div>

	<div class="field-description ac-error">
		<?php echo __( 'No forms available!', 'thrive-cb' ); ?>
	</div>
</div>
<div class="api-field">
	<div class="row">
		<div class="col-xs-12">
			<div class="tvd-input-field">
				<input id="activecampaign_tags" type="text" class="tve-api-extra" name="tags" value="<#= api.getConfig('tags') ? api.getConfig('tags') : '' #>"/>
				<label for="activecampaign_tags"><?php echo __( 'Tags', 'thrive-cb' ) ?></label>
			</div>
		</div>
	</div>
	<div class="field-description"><?php echo __( 'Comma-separated lists of tags to assign to a new contact in ActiveCampaign', 'thrive-cb' ); ?></div>
</div>
