<h4><?php echo __('Select a campaign to move to or create a new evergreen campaign', TVE_Ult_Const::T) ?></h4>
<div id="tvu-campaign-move-wrapper" class="tvd-row"></div>
<# if(collection.length === 0) { #>
	<p><?php echo __( "There are no Evergreen Campaigns to move to", TVE_Ult_Const::T ); ?></p>
<# } #>
<a href="javascript:void(0)" id="tvu-add-evergreen-campaign" class="tvu-add-evergreen-campaign tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-blue tvd-btn-small tvd-inline-block"><?php echo __('+ Add New', TVE_Ult_Const::T) ?></a>
<div class="tvd-v-spacer"></div>


