<h3 class="tvd-title"><?php echo __( 'Archived Campaigns', TVE_Ult_Const::T ) ?></h3>

<div id="tvu-no-campaign-text">
	<p>
		<?php echo sprintf(
			__( 'No archived campaigns.', TVE_Ult_Const::T )
		) ?>
	</p>

</div>

<div class="tvd-v-spacer"></div>

<div class="tvd-row" id="tvu-campaigns-list"></div>

<div class="tvd-row">
	<div class="tvd-col tvd-s6">
		<a href="#purge-cache" class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-dark tvd-waves-effect">
			&laquo; <?php echo __( 'Back to Dashboard', TVE_Ult_Const::T ) ?>
		</a>
	</div>
</div>
