<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php echo __( "Copy campaign - ", TVE_Ult_Const::T ) ?>
		<#= model.get('post_title') #>
	</h3>
	<div class="tvd-v-spacer"></div>
	<div class="tvu-new-campaign-templates tvd-row tvd-collapse"></div>
	<div class="tvd-col tvd-s12" id="tvu-campaign-type-options"></div>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
				<?php echo __( "Cancel", TVE_Ult_Const::T ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tvd-modal-submit">
				<?php echo __( "Copy", TVE_Ult_Const::T ) ?>
			</a>
		</div>
	</div>
</div>

