<div class="tve-password-strength-wrapper">
	<div class="tve-password-strength tve-password-strength-0"></div>
	<div class="tve-password-strength tve-password-strength-1"></div>
	<div class="tve-password-strength tve-password-strength-2"></div>
	<div class="tve-password-strength tve-password-strength-3"></div>
	<span class="tve-password-strength-icon"></span>
	<span class="tve-password-strength-text"></span>
</div>
