<div class="row">
	<div class="col-xs-6">
		<div class="group-label grey-text">
			<?php echo __( 'Style', 'thrive-cb' ) ?>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="button-group-holder">
			<div class="tve-btn-group">
				<div class="btn-inline tve-btn icon-medium click padded tve-divider-zigzag" data-fn="setStyle" data-style="zigzag" title="Zig Zag">
					<svg class="tcb-icon tcb-icon-open-lightbox">
						<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-S1"></use>
					</svg>
				</div>
				<div class="btn-inline tve-btn click icon-medium padded tve-divider-curves" data-fn="setStyle" data-style="curves" title="Curves">
					<svg class="tcb-icon tcb-icon-open-lightbox">
						<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-S2"></use>
					</svg>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="tve-divider-sliders">
	<div class="row">
		<div class="col-xs-12">
			<div class="tve-control tve-divider-width"></div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<div class="tve-control tve-divider-height"></div>
		</div>
	</div>
</div>
