<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 2/9/2018
 * Time: 2:48 PM
 */
?>
<label><?php echo __( 'Select Background Effect', 'thrive-cb' ) ?></label>
<div class="drop-panel-control tcb-background-effect-select tve-control"></div>
<div class="drop-panel-control tcb-background-effect-slider tve-control" data-key="opacity"></div>
<div class="drop-panel-control tcb-background-effect-slider tve-control" data-key="grayscale"></div>
<div class="drop-panel-control tcb-background-effect-slider tve-control" data-key="blur"></div>
