<div class="row">
	<div class="col-xs-5 border-boxes">
		<div class="tve-border-side click top" data-fn="borderSide" data-value="top"></div>
		<div class="tve-border-side click left" data-fn="borderSide" data-value="left"></div>
		<div class="tve-border-side click right" data-fn="borderSide" data-value="right"></div>
		<div class="tve-border-side click bottom" data-fn="borderSide" data-value="bottom"></div>
		<div class="tve-border-side default center click" data-fn="borderSide" data-value=""></div>
	</div>
	<div class="col-xs-7">
		<div class="tve-border-settings">
			<div class="row">
				<div class="col-xs-8">
					<div class="tve-border-width"></div>
				</div>
				<div class="col-xs-4">
					<div class="tve-border-color hide-input"></div>
				</div>
			</div>

			<div class="tve-border-style"></div>
		</div>
	</div>
</div>
