<div class="row">
	<div class="col-xs-5 corner-boxes">
		<div class="tve-corner click top-left" data-fn="corner" data-value="top-left"></div>
		<div class="tve-corner click top-right" data-fn="corner" data-value="top-right"></div>
		<div class="tve-corner click bottom-right" data-fn="corner" data-value="bottom-right"></div>
		<div class="tve-corner click bottom-left" data-fn="corner" data-value="bottom-left"></div>
		<div class="tve-corner click default center" data-fn="corner" data-value=""></div>
	</div>
	<div class="col-xs-7 corner-radius">
		<div class="tve-corner-value"></div>
	</div>
</div>
