<div class="row middle-xs">
	<div class="col-xs-2">
		<div class="input-label"><?php echo __( 'Icon', 'thrive-cb' ); ?></div>
	</div>
	<div class="col-xs-10 tcb-input-button-wrapper">
		<div class="col-sep click" data-fn="openModal"></div>
		<input type="text" class="style-change-input click" data-fn="openModal" readonly value="<?php echo __( 'None', 'thrive-cb' ); ?>">
		<?php tcb_icon( 'edit', false, 'sidebar', 'tcb-input-button click', array( 'data-fn' => 'openModal' ) ) ?>
	</div>
</div>