<div class="row middle-xs between-xs">
	<div class="col-xs-3"><?php echo __( 'Rating', 'thrive-cb' ) ?></div>
	<div class="col-xs-3"><select class="rating-value change" data-fn="option_changed"></select></div>
	<div class="col-xs-3 tcb-text-right"><?php echo __( 'out of', 'thrive-cb' ) ?></div>
	<div class="col-xs-3"><select class="rating-max change" data-fn="option_changed"></select></div>
</div>
