<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 2/27/2017
 * Time: 3:27 PM
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="styles-templates-options action-group">
	<div class="dropdown-header" data-prop="docked">
		<span>
			<?php echo __( 'Styles & Templates', 'thrive-cb' ); ?>
		</span>
		<i></i>
	</div>
	<div class="dropdown-content">
		<div class="tcb-style-template-step">
			<div class="tve-control" data-input="class"></div>
			<div class="tve-control padding-top-10" data-input="id"></div>
			<div class="row padding-top-20 padding-bottom-10">
				<div class="col-xs-6">
					<button class="tve-button click blue" data-fn="clear_styles"><?php echo __( 'Clear Styles', 'thrive-cb' ); ?></button>
				</div>
				<div class="col-xs-6">
					<button class="tve-button click green" data-fn="next"><?php echo __( 'Save Template', 'thrive-cb' ); ?></button>
				</div>
			</div>
		</div>
		<div class="tcb-style-template-step">
			<div class="row">
				<div class="col-xs-12">
					<span class="grey-text"><?php echo __( 'Template Name', 'thrive-cb' ); ?></span>
				</div>
			</div>
			<div class="row padding-top-10">
				<div class="col-xs-12">
					<input type="text" id="tcb-template-name" class="keyup" data-fn="handle_keyup_save"/>
				</div>
			</div>
			<div class="yt-url-validate inline-message"></div>
			<div class="row">
				<div class="col-xs-12 tcb-checkbox">
					<input type="checkbox" id="tcb-add-template-categ-check" class="click" data-fn="show_hide_tpl_category"/>
					<label for="tcb-add-template-categ-check"><?php echo __( 'Add template to a category', 'thrive-cb' ); ?></label>
				</div>
			</div>
			<div class="row padding-top-10 tcb-hidden" id="tcb-select-category-row">
				<div class="col-xs-12">
					<span class="grey-text"><?php echo __( 'Select a category', 'thrive-cb' ); ?></span>
				</div>
				<div class="col-xs-12 padding-top-10">
					<select id="tcb-template-categ-suggest"></select>
					<input type="hidden" id="tcb-template-category-id" value=""/>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="col-xs-12">
					<a href="<?php echo admin_url( 'admin.php?page=tcb_admin_dashboard' ); ?>" target="_blank">
						<span class="blue-text"><?php tcb_icon( 'info' ); ?></span>
						<span class="info-text"><?php echo __( 'Manage content templates', 'thrive-cb' ); ?></span>
					</a>
				</div>
			</div>
			<div class="row padding-top-10 padding-bottom-10">
				<div class="col-xs-6">
					<button class="tve-button click grey" data-fn="prev"><?php echo __( 'Cancel', 'thrive-cb' ); ?></button>
				</div>
				<div class="col-xs-6">
					<button class="tve-button click green" data-fn="save_template"><?php echo __( 'Save Template', 'thrive-cb' ); ?></button>
				</div>
			</div>
		</div>
	</div>
</div>
