<div class="row middle-xs between-xs">
	<div class="col-xs-2">
		<span class="input-label"><#=this.model.config.label#></span>
	</div>
	<div class="col-xs-10 tcb-input-button-wrapper">
		<div class="col-sep click" data-fn="open_panel"></div>
		<input type="text" class="style-change-input click" data-fn="open_panel" readonly>
		<?php tcb_icon( 'edit', false, 'sidebar', 'tcb-input-button click', array( 'data-fn' => 'open_panel' ) ) ?>
	</div>
</div>
