<div class="tve-api-card">
	<div class="tve-api-image click" data-fn="step" data-template="edit" data-api="<#= this.model.get('key') #>" style="background-image: url('<#= this.model.logo() #>');"></div>
	<div class="row">
		<div class="col-sm-12 padding-left-5">
			<h4 class="margin-top-10 padding-left-10 click" data-api="<#= this.model.get('key') #>" data-fn="step" data-template="edit">
				<#= this.model.get('name') #>
			</h4>
		</div>
	</div>
</div>
