<div class="tcb-right">
	<a class="button-link blue" target="_blank" href="<?php echo admin_url( 'admin.php?page=tve_dash_api_connect#tve_new_api' ); ?>">
		<?php echo __( 'Add new API Connections', 'thrive-cb' ) ?>
	</a>
</div>
<h3>
	<?php echo __( 'Chose an already created API or create a new one.', 'thrive-cb' ); ?>
</h3>
<div class="tve-api-list row"></div>

<div class="tcb-modal-footer clearfix padding-top-20 row end-xs">
	<div class="col col-xs-6">
		<button type="button" class="tcb-left tve-button grey click tve-custom-html-action" data-fn="step" data-template="form" data-next="0">
			<?php echo __( 'Switch to HTML Integration', 'thrive-cb' ); ?>
		</button>
	</div>
	<div class="col col-xs-6"></div>
</div>
