<div class="connection-setup"></div>

<div class="row margin-top-10">
	<div class="col-sm-6">
		<button type="button" class="tve-button grey click" data-fn="step" data-template="apis" data-next="0">
			<?php echo __( 'Discard', 'thrive-cb' ); ?>
		</button>
	</div>

	<div class="col-sm-6">
		<button type="button" class="tcb-right tve-button green click" data-fn="step" data-template="fields">
			<?php echo __( 'Continue', 'thrive-cb' ); ?>
		</button>
	</div>
</div>
