<textarea id="lead_generation_code" class="margin-top-20" placeholder="<?php echo __( 'Insert your code here', 'thrive-cb' ); ?>"></textarea>

<div class="tcb-modal-footer clearfix padding-top-20 row end-xs">
	<div class="col col-xs-6">
		<button type="button" class="tcb-left tve-button grey click" data-fn="step" data-template="apis" data-next="0">
			<?php echo __( 'Switch to API Integration', 'thrive-cb' ); ?>
		</button>
	</div>

	<div class="col col-xs-6">
		<button type="button" class="tcb-right tve-button green click" data-fn="parseHTML">
			<?php echo __( 'Continue', 'thrive-cb' ); ?>
		</button>
	</div>
</div>
