<div class="api-field">
	<label class="tcb-checkbox">
		<input id="tve-create-account" class="tve-api-extra tve-checkbox" type="checkbox" value="1" <#= redirect? 'checked': '' #>>
		<span><?php echo __( 'Redirect to Account Creation Page', 'thrive-leads' ); ?></span>
	</label>
	<div class="field-description margin-top-10">
		<?php echo __( 'by checking this, the form will pass the form data to the page where the account creation is made.', 'thrive-leads' ); ?>
	</div>
</div>