<?php
$_default_errors = array(
	'email'            => __( 'Email address invalid', 'thrive-cb' ),
	'phone'            => __( 'Phone number invalid', 'thrive-cb' ),
	'password'         => __( 'Password invalid', 'thrive-cb' ),
	'passwordmismatch' => __( 'Password mismatch error', 'thrive-cb' ),
	'required'         => __( 'Required field missing', 'thrive-cb' ),
);
?>
<input type="hidden" class="tve-lg-err-msg" value="<?php echo htmlspecialchars( json_encode( $_default_errors ) ) ?>">
<div class="thrv_lead_generation_container tve_clearfix">
	<form action="#" method="post" novalidate="">
		<div class="tve_lead_generated_inputs_container tve_clearfix">
			<div class="tve_lg_input_container tve_lg_input">
				<input type="text" data-field="name" name="name" placeholder="Name" data-placeholder="Name">
			</div>
			<div class="tve_lg_input_container tve_lg_input">
				<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email">
			</div>
			<div class="tve_lg_input_container tve_submit_container tve_lg_submit">
				<button type="submit"><?php echo __( 'Sign Up', 'thrive-cb' ); ?></button>
			</div>
		</div>
	</form>
</div>
