<div class="row">
	<div class="col-xs-5 group-label grey-text margin-top-5">
		<?php echo __( 'Menu Display', 'thrive-cb' ); ?>
	</div>
	<div class="col-xs-7">
		<select class="tve-select change" data-fn="changeDirection">
			<option value="tve_horizontal"><?php echo __( 'Horizontal', 'thrive-cb' ); ?></option>
			<option value="tve_vertical"><?php echo __( 'Vertical', 'thrive-cb' ); ?></option>
		</select>
	</div>
</div>
