<div class="row column-options">
	<div class="col-xs-4">
		<div class="panel-title"><?php echo sprintf( __( '%d Columns', 'thrive-cb' ), 2 ) ?></div>
	</div>
	<div class="col-xs-4">
		<div class="panel-title"><?php echo sprintf( __( '%d Columns', 'thrive-cb' ), 3 ) ?></div>
	</div>
	<div class="col-xs-4">
		<div class="panel-title"><?php echo sprintf( __( '%d Columns', 'thrive-cb' ), 4 ) ?></div>
	</div>
</div>
<div class="row tcb-col-preview tcb-text-center">
	<div class="col-xs-4" data-cols="2">
		<div class="row click" data-fn="render_row">
			<div class="col-xs-6">
				<div class="desc">1/2</div>
			</div>
			<div class="col-xs-6">
				<div class="desc">1/2</div>
			</div>
		</div>
		<div class="row click" data-fn="render_row">
			<div class="c-33 col-xs-4">
				<div class="desc">1/3</div>
			</div>
			<div class="c-66 col-xs-8">
				<div class="desc">2/3</div>
			</div>
		</div>
		<div class="row click" data-fn="render_row">
			<div class="c-66 col-xs-8">
				<div class="desc">2/3</div>
			</div>
			<div class="c-33 col-xs-4">
				<div class="desc">1/3</div>
			</div>
		</div>
	</div>
	<div class="col-xs-4" data-cols="3">
		<div class="row click" data-fn="render_row">
			<div class="col-xs-4">
				<div class="desc">1/3</div>
			</div>
			<div class="col-xs-4">
				<div class="desc">1/3</div>
			</div>
			<div class="col-xs-4">
				<div class="desc">1/3</div>
			</div>
		</div>
		<div class="row click" data-fn="render_row">
			<div class="c-25 col-xs-3">
				<div class="desc">1/4</div>
			</div>
			<div class="c-50 col-xs-6">
				<div class="desc">2/4</div>
			</div>
			<div class="c-25 col-xs-3">
				<div class="desc">1/4</div>
			</div>
		</div>
		<div class="row click" data-fn="render_row">
			<div class="c-25 col-xs-3">
				<div class="desc">1/4</div>
			</div>
			<div class="c-25 col-xs-3">
				<div class="desc">1/4</div>
			</div>
			<div class="c-50 col-xs-6">
				<div class="desc">2/4</div>
			</div>
		</div>
		<div class="row click" data-fn="render_row">
			<div class="c-50 col-xs-6">
				<div class="desc">2/4</div>
			</div>
			<div class="c-25 col-xs-3">
				<div class="desc">1/4</div>
			</div>
			<div class="c-25 col-xs-3">
				<div class="desc">1/4</div>
			</div>
		</div>
	</div>
	<div class="col-xs-4" data-cols="4">
		<div class="row click" data-fn="render_row">
			<div class="col-xs-3">
				<div class="desc">1/4</div>
			</div>
			<div class="col-xs-3">
				<div class="desc">1/4</div>
			</div>
			<div class="col-xs-3">
				<div class="desc">1/4</div>
			</div>
			<div class="col-xs-3">
				<div class="desc">1/4</div>
			</div>
		</div>
	</div>
</div>
