<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 3/7/2018
 * Time: 9:17 AM
 */
?>
<div class="row">
	<div class="col-xs-6 tcb-top-responsive">
		<?php echo __( 'Edit fonts for:', 'thrive-cb' ); ?>
	</div>
	<div class="col-xs-6 tcb-top-responsive tcb-responsive-buttons-wrapper">
		<div class="row">
			<div class="col-xs-4 click" data-fn="change_inline_preview" data-device="desktop"><?php tcb_icon( 'desktop' ); ?></div>
			<div class="col-xs-4 click" data-fn="change_inline_preview" data-device="tablet"><?php tcb_icon( 'tablet2' ); ?></div>
			<div class="col-xs-4 click" data-fn="change_inline_preview" data-device="mobile"><?php tcb_icon( 'mobile' ); ?></div>
		</div>
	</div>
</div>
