<div class="tvd-card tvd-medium-xxsmall tvd-red tve-delete-design-card" tabindex="-1">
	<div class="tvd-card-content tvd-center-align">
		<h4 class="tvd-margin-top">
			<?php echo __( 'Are you sure you want to delete this design?', TVE_Ult_Const::T ) ?>
		</h4>
		<p>
			<?php echo __( 'By deleting a design you will also delete the actions related to it on the timeline.', TVE_Ult_Const::T ) ?>
		</p>
	</div>
	<div class="tvd-card-action">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6">
				<a class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tvd-left tvu-delete-yes">
					<?php echo __( "Yes, delete", TVE_Ult_Const::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6">
				<a class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-right tvu-delete-no">
					<?php echo __( "No, keep it", TVE_Ult_Const::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
