<div class="row">
	<div class="col-xs-3 margin-right-10">
		<div class="api-image" style="background-image: url('<#= this.model.logo() #>');"></div>
	</div>
	<div class="col-xs-8 margin-top-10">
		<div class="api-name margin-bottom-5 margin-left-5">
			<#= TVE.ucFirst(this.model.get('name')) #>
		</div>
		<button type="button" class="button-link blue click" data-fn="edit" data-api="<#= this.model.get('key') #>">
			<?php echo __( 'Edit', 'thrive-cb' ); ?>
		</button>
		<button type="button" class="button-link red click" data-fn="disconnect" data-api="<#= this.model.get('key') #>">
			<?php echo __( 'Disconnect', 'thrive-cb' ); ?>
		</button>
	</div>
</div>
